/* StatusIcon.vala.c generated by valac 0.24.0, the Vala compiler
 * generated from StatusIcon.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define TYPE_STATUS_ICON_A (status_icon_a_get_type ())
#define STATUS_ICON_A(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STATUS_ICON_A, StatusIconA))
#define STATUS_ICON_A_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_STATUS_ICON_A, StatusIconAClass))
#define IS_STATUS_ICON_A(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STATUS_ICON_A))
#define IS_STATUS_ICON_A_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_STATUS_ICON_A))
#define STATUS_ICON_A_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_STATUS_ICON_A, StatusIconAClass))

typedef struct _StatusIconA StatusIconA;
typedef struct _StatusIconAClass StatusIconAClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _StatusIconAPrivate StatusIconAPrivate;

#define STATUS_ICON_A_TYPE_MENU_A (status_icon_a_menu_a_get_type ())
#define STATUS_ICON_A_MENU_A(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_TYPE_MENU_A, StatusIconAMenuA))
#define STATUS_ICON_A_MENU_A_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_TYPE_MENU_A, StatusIconAMenuAClass))
#define STATUS_ICON_A_IS_MENU_A(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_TYPE_MENU_A))
#define STATUS_ICON_A_IS_MENU_A_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_TYPE_MENU_A))
#define STATUS_ICON_A_MENU_A_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_TYPE_MENU_A, StatusIconAMenuAClass))

typedef struct _StatusIconAMenuA StatusIconAMenuA;
typedef struct _StatusIconAMenuAClass StatusIconAMenuAClass;
typedef struct _Block1Data Block1Data;
typedef struct _StatusIconAMenuAPrivate StatusIconAMenuAPrivate;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A (status_icon_a_menu_a_image_menu_item_a_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_A(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A, StatusIconAMenuAImageMenuItemA))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_A_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A, StatusIconAMenuAImageMenuItemAClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_A(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_A_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_A_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A, StatusIconAMenuAImageMenuItemAClass))

typedef struct _StatusIconAMenuAImageMenuItemA StatusIconAMenuAImageMenuItemA;
typedef struct _StatusIconAMenuAImageMenuItemAClass StatusIconAMenuAImageMenuItemAClass;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B (status_icon_a_menu_a_image_menu_item_b_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_B(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B, StatusIconAMenuAImageMenuItemB))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_B_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B, StatusIconAMenuAImageMenuItemBClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_B(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_B_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_B_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B, StatusIconAMenuAImageMenuItemBClass))

typedef struct _StatusIconAMenuAImageMenuItemB StatusIconAMenuAImageMenuItemB;
typedef struct _StatusIconAMenuAImageMenuItemBClass StatusIconAMenuAImageMenuItemBClass;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C (status_icon_a_menu_a_image_menu_item_c_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_C(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C, StatusIconAMenuAImageMenuItemC))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_C_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C, StatusIconAMenuAImageMenuItemCClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_C(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_C_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_C_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C, StatusIconAMenuAImageMenuItemCClass))

typedef struct _StatusIconAMenuAImageMenuItemC StatusIconAMenuAImageMenuItemC;
typedef struct _StatusIconAMenuAImageMenuItemCClass StatusIconAMenuAImageMenuItemCClass;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D (status_icon_a_menu_a_image_menu_item_d_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_D(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D, StatusIconAMenuAImageMenuItemD))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_D_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D, StatusIconAMenuAImageMenuItemDClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_D(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_D_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_D_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D, StatusIconAMenuAImageMenuItemDClass))

typedef struct _StatusIconAMenuAImageMenuItemD StatusIconAMenuAImageMenuItemD;
typedef struct _StatusIconAMenuAImageMenuItemDClass StatusIconAMenuAImageMenuItemDClass;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E (status_icon_a_menu_a_image_menu_item_e_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_E(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E, StatusIconAMenuAImageMenuItemE))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_E_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E, StatusIconAMenuAImageMenuItemEClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_E(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_E_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_E_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E, StatusIconAMenuAImageMenuItemEClass))

typedef struct _StatusIconAMenuAImageMenuItemE StatusIconAMenuAImageMenuItemE;
typedef struct _StatusIconAMenuAImageMenuItemEClass StatusIconAMenuAImageMenuItemEClass;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F (status_icon_a_menu_a_image_menu_item_f_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_F(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F, StatusIconAMenuAImageMenuItemF))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_F_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F, StatusIconAMenuAImageMenuItemFClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_F(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_F_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_F_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F, StatusIconAMenuAImageMenuItemFClass))

typedef struct _StatusIconAMenuAImageMenuItemF StatusIconAMenuAImageMenuItemF;
typedef struct _StatusIconAMenuAImageMenuItemFClass StatusIconAMenuAImageMenuItemFClass;

#define STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G (status_icon_a_menu_a_image_menu_item_g_get_type ())
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_G(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G, StatusIconAMenuAImageMenuItemG))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_G_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G, StatusIconAMenuAImageMenuItemGClass))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_G(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G))
#define STATUS_ICON_A_MENU_A_IS_IMAGE_MENU_ITEM_G_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G))
#define STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_G_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G, StatusIconAMenuAImageMenuItemGClass))

typedef struct _StatusIconAMenuAImageMenuItemG StatusIconAMenuAImageMenuItemG;
typedef struct _StatusIconAMenuAImageMenuItemGClass StatusIconAMenuAImageMenuItemGClass;
typedef struct _StatusIconAMenuAImageMenuItemAPrivate StatusIconAMenuAImageMenuItemAPrivate;
typedef struct _StatusIconAMenuAImageMenuItemBPrivate StatusIconAMenuAImageMenuItemBPrivate;
typedef struct _StatusIconAMenuAImageMenuItemCPrivate StatusIconAMenuAImageMenuItemCPrivate;
typedef struct _StatusIconAMenuAImageMenuItemDPrivate StatusIconAMenuAImageMenuItemDPrivate;
typedef struct _StatusIconAMenuAImageMenuItemEPrivate StatusIconAMenuAImageMenuItemEPrivate;
typedef struct _StatusIconAMenuAImageMenuItemFPrivate StatusIconAMenuAImageMenuItemFPrivate;
typedef struct _StatusIconAMenuAImageMenuItemGPrivate StatusIconAMenuAImageMenuItemGPrivate;

struct _StatusIconA {
	GtkStatusIcon parent_instance;
	StatusIconAPrivate * priv;
};

struct _StatusIconAClass {
	GtkStatusIconClass parent_class;
};

struct _StatusIconAPrivate {
	gboolean paused;
};

struct _Block1Data {
	int _ref_count_;
	StatusIconA* self;
	StatusIconAMenuA* menu;
};

struct _StatusIconAMenuA {
	GtkMenu parent_instance;
	StatusIconAMenuAPrivate * priv;
	GtkImageMenuItem* pause;
	GtkImageMenuItem* resume;
};

struct _StatusIconAMenuAClass {
	GtkMenuClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemA {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemAPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemAClass {
	GtkImageMenuItemClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemB {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemBPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemBClass {
	GtkImageMenuItemClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemC {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemCPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemCClass {
	GtkImageMenuItemClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemD {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemDPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemDClass {
	GtkImageMenuItemClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemE {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemEPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemEClass {
	GtkImageMenuItemClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemF {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemFPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemFClass {
	GtkImageMenuItemClass parent_class;
};

struct _StatusIconAMenuAImageMenuItemG {
	GtkImageMenuItem parent_instance;
	StatusIconAMenuAImageMenuItemGPrivate * priv;
};

struct _StatusIconAMenuAImageMenuItemGClass {
	GtkImageMenuItemClass parent_class;
};


static gpointer status_icon_a_parent_class = NULL;
static StatusIconA* status_icon_a_statusicon;
static StatusIconA* status_icon_a_statusicon = NULL;
static gpointer status_icon_a_menu_a_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_a_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_b_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_c_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_d_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_e_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_f_parent_class = NULL;
static gpointer status_icon_a_menu_a_image_menu_item_g_parent_class = NULL;

gint _vala_main (gchar** args, int args_length1);
StatusIconA* status_icon_a_new (void);
StatusIconA* status_icon_a_construct (GType object_type);
GType status_icon_a_get_type (void) G_GNUC_CONST;
#define STATUS_ICON_A_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_STATUS_ICON_A, StatusIconAPrivate))
enum  {
	STATUS_ICON_A_DUMMY_PROPERTY
};
static GType status_icon_a_menu_a_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static StatusIconAMenuA* status_icon_a_menu_a_new (void);
static StatusIconAMenuA* status_icon_a_menu_a_construct (GType object_type);
static void __lambda10_ (Block1Data* _data1_);
static void _gtk_status_icon_position_menu_gtk_menu_position_func (GtkMenu* menu, gint* x, gint* y, gboolean* push_in, gpointer self);
static void ___lambda10__gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_DUMMY_PROPERTY
};
static StatusIconAMenuAImageMenuItemA* status_icon_a_menu_a_image_menu_item_a_new (void);
static StatusIconAMenuAImageMenuItemA* status_icon_a_menu_a_image_menu_item_a_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_a_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static StatusIconAMenuAImageMenuItemB* status_icon_a_menu_a_image_menu_item_b_new (void);
static StatusIconAMenuAImageMenuItemB* status_icon_a_menu_a_image_menu_item_b_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_b_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static StatusIconAMenuAImageMenuItemC* status_icon_a_menu_a_image_menu_item_c_new (void);
static StatusIconAMenuAImageMenuItemC* status_icon_a_menu_a_image_menu_item_c_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_c_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static StatusIconAMenuAImageMenuItemD* status_icon_a_menu_a_image_menu_item_d_new (void);
static StatusIconAMenuAImageMenuItemD* status_icon_a_menu_a_image_menu_item_d_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_d_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static StatusIconAMenuAImageMenuItemE* status_icon_a_menu_a_image_menu_item_e_new (void);
static StatusIconAMenuAImageMenuItemE* status_icon_a_menu_a_image_menu_item_e_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_e_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static StatusIconAMenuAImageMenuItemF* status_icon_a_menu_a_image_menu_item_f_new (void);
static StatusIconAMenuAImageMenuItemF* status_icon_a_menu_a_image_menu_item_f_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_f_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static StatusIconAMenuAImageMenuItemG* status_icon_a_menu_a_image_menu_item_g_new (void);
static StatusIconAMenuAImageMenuItemG* status_icon_a_menu_a_image_menu_item_g_construct (GType object_type);
static GType status_icon_a_menu_a_image_menu_item_g_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_A_DUMMY_PROPERTY
};
static void __lambda3_ (StatusIconAMenuAImageMenuItemA* self);
static void ___lambda3__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_B_DUMMY_PROPERTY
};
static void __lambda4_ (StatusIconAMenuAImageMenuItemB* self);
static void ___lambda4__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_C_DUMMY_PROPERTY
};
static void __lambda5_ (StatusIconAMenuAImageMenuItemC* self);
static void ___lambda5__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_D_DUMMY_PROPERTY
};
static void __lambda6_ (StatusIconAMenuAImageMenuItemD* self);
static void ___lambda6__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_E_DUMMY_PROPERTY
};
static void __lambda7_ (StatusIconAMenuAImageMenuItemE* self);
static void ___lambda7__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_F_DUMMY_PROPERTY
};
static void __lambda8_ (StatusIconAMenuAImageMenuItemF* self);
static void ___lambda8__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
enum  {
	STATUS_ICON_A_MENU_A_IMAGE_MENU_ITEM_G_DUMMY_PROPERTY
};
static void __lambda9_ (StatusIconAMenuAImageMenuItemG* self);
static void ___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void status_icon_a_menu_a_finalize (GObject* obj);
static void status_icon_a_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
 * Status icon and menu for component of gitlive.
 * 
 * Implements XObject - however we want to control initialization.
 * 
 * 
 * 
 * Currently only does a few things
 * a) Quit
 * 
 * b) Pause!??!
 */
gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	StatusIconA* _tmp0_ = NULL;
	StatusIconA* _tmp1_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = status_icon_a_new ();
	_tmp1_ = _tmp0_;
	_g_object_unref0 (_tmp1_);
	gtk_main ();
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		StatusIconA* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->menu);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _gtk_status_icon_position_menu_gtk_menu_position_func (GtkMenu* menu, gint* x, gint* y, gboolean* push_in, gpointer self) {
	gtk_status_icon_position_menu (menu, x, y, push_in, (GtkStatusIcon*) self);
}


static void __lambda10_ (Block1Data* _data1_) {
	StatusIconA* self;
	gboolean _tmp0_ = FALSE;
	guint32 _tmp5_ = 0U;
	self = _data1_->self;
	gtk_widget_show_all ((GtkWidget*) _data1_->menu);
	_tmp0_ = self->priv->paused;
	if (_tmp0_) {
		GtkImageMenuItem* _tmp1_ = NULL;
		GtkImageMenuItem* _tmp2_ = NULL;
		_tmp1_ = _data1_->menu->resume;
		gtk_widget_show ((GtkWidget*) _tmp1_);
		_tmp2_ = _data1_->menu->pause;
		gtk_widget_hide ((GtkWidget*) _tmp2_);
	} else {
		GtkImageMenuItem* _tmp3_ = NULL;
		GtkImageMenuItem* _tmp4_ = NULL;
		_tmp3_ = _data1_->menu->resume;
		gtk_widget_hide ((GtkWidget*) _tmp3_);
		_tmp4_ = _data1_->menu->pause;
		gtk_widget_show ((GtkWidget*) _tmp4_);
	}
	_tmp5_ = gtk_get_current_event_time ();
	gtk_menu_popup ((GtkMenu*) _data1_->menu, NULL, NULL, _gtk_status_icon_position_menu_gtk_menu_position_func, (GtkStatusIcon*) self, (guint) 0, _tmp5_);
}


static void ___lambda10__gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self) {
	__lambda10_ (self);
}


StatusIconA* status_icon_a_construct (GType object_type) {
	StatusIconA * self = NULL;
	Block1Data* _data1_;
	StatusIconA* _tmp0_ = NULL;
	StatusIconAMenuA* _tmp1_ = NULL;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	self = (StatusIconA*) g_object_new (object_type, NULL);
	_data1_->self = g_object_ref (self);
	_tmp0_ = _g_object_ref0 (self);
	_g_object_unref0 (status_icon_a_statusicon);
	status_icon_a_statusicon = _tmp0_;
	g_object_set ((GtkStatusIcon*) self, "stock", GTK_STOCK_REFRESH, NULL);
	gtk_status_icon_set_tooltip_text ((GtkStatusIcon*) self, "GitLive");
	gtk_status_icon_set_title ((GtkStatusIcon*) self, "vgitlive");
	gtk_status_icon_set_name ((GtkStatusIcon*) self, "vgitlive");
	gtk_status_icon_set_visible ((GtkStatusIcon*) self, TRUE);
	_tmp1_ = status_icon_a_menu_a_new ();
	g_object_ref_sink (_tmp1_);
	_data1_->menu = _tmp1_;
	g_signal_connect_data ((GtkStatusIcon*) self, "activate", (GCallback) ___lambda10__gtk_status_icon_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return self;
}


StatusIconA* status_icon_a_new (void) {
	return status_icon_a_construct (TYPE_STATUS_ICON_A);
}


static StatusIconAMenuA* status_icon_a_menu_a_construct (GType object_type) {
	StatusIconAMenuA * self = NULL;
	StatusIconAMenuAImageMenuItemA* _tmp0_ = NULL;
	GtkImageMenuItem* _tmp1_ = NULL;
	StatusIconAMenuAImageMenuItemB* _tmp2_ = NULL;
	GtkImageMenuItem* _tmp3_ = NULL;
	StatusIconAMenuAImageMenuItemC* _tmp4_ = NULL;
	StatusIconAMenuAImageMenuItemC* _tmp5_ = NULL;
	StatusIconAMenuAImageMenuItemD* _tmp6_ = NULL;
	StatusIconAMenuAImageMenuItemD* _tmp7_ = NULL;
	StatusIconAMenuAImageMenuItemE* _tmp8_ = NULL;
	StatusIconAMenuAImageMenuItemE* _tmp9_ = NULL;
	StatusIconAMenuAImageMenuItemF* _tmp10_ = NULL;
	StatusIconAMenuAImageMenuItemF* _tmp11_ = NULL;
	StatusIconAMenuAImageMenuItemG* _tmp12_ = NULL;
	StatusIconAMenuAImageMenuItemG* _tmp13_ = NULL;
	self = (StatusIconAMenuA*) g_object_new (object_type, NULL);
	_tmp0_ = status_icon_a_menu_a_image_menu_item_a_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->pause);
	self->pause = (GtkImageMenuItem*) _tmp0_;
	_tmp1_ = self->pause;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp1_));
	_tmp2_ = status_icon_a_menu_a_image_menu_item_b_new ();
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->resume);
	self->resume = (GtkImageMenuItem*) _tmp2_;
	_tmp3_ = self->resume;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp3_));
	_tmp4_ = status_icon_a_menu_a_image_menu_item_c_new ();
	g_object_ref_sink (_tmp4_);
	_tmp5_ = _tmp4_;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp5_));
	_g_object_unref0 (_tmp5_);
	_tmp6_ = status_icon_a_menu_a_image_menu_item_d_new ();
	g_object_ref_sink (_tmp6_);
	_tmp7_ = _tmp6_;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp7_));
	_g_object_unref0 (_tmp7_);
	_tmp8_ = status_icon_a_menu_a_image_menu_item_e_new ();
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp9_));
	_g_object_unref0 (_tmp9_);
	_tmp10_ = status_icon_a_menu_a_image_menu_item_f_new ();
	g_object_ref_sink (_tmp10_);
	_tmp11_ = _tmp10_;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp11_));
	_g_object_unref0 (_tmp11_);
	_tmp12_ = status_icon_a_menu_a_image_menu_item_g_new ();
	g_object_ref_sink (_tmp12_);
	_tmp13_ = _tmp12_;
	gtk_menu_shell_append ((GtkMenuShell*) self, (GtkWidget*) ((GtkMenuItem*) _tmp13_));
	_g_object_unref0 (_tmp13_);
	return self;
}


static StatusIconAMenuA* status_icon_a_menu_a_new (void) {
	return status_icon_a_menu_a_construct (STATUS_ICON_A_TYPE_MENU_A);
}


static void __lambda3_ (StatusIconAMenuAImageMenuItemA* self) {
	StatusIconA* _tmp0_ = NULL;
	StatusIconA* _tmp1_ = NULL;
	_tmp0_ = status_icon_a_statusicon;
	_tmp0_->priv->paused = TRUE;
	_tmp1_ = status_icon_a_statusicon;
	gtk_status_icon_set_from_stock ((GtkStatusIcon*) _tmp1_, GTK_STOCK_MEDIA_PAUSE);
}


static void ___lambda3__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda3_ ((StatusIconAMenuAImageMenuItemA*) self);
}


static StatusIconAMenuAImageMenuItemA* status_icon_a_menu_a_image_menu_item_a_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemA * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemA*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_MEDIA_PAUSE, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "Pause Commits");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda3__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemA* status_icon_a_menu_a_image_menu_item_a_new (void) {
	return status_icon_a_menu_a_image_menu_item_a_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_A);
}


static void status_icon_a_menu_a_image_menu_item_a_class_init (StatusIconAMenuAImageMenuItemAClass * klass) {
	status_icon_a_menu_a_image_menu_item_a_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_a_instance_init (StatusIconAMenuAImageMenuItemA * self) {
}


static GType status_icon_a_menu_a_image_menu_item_a_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_a_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_a_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemAClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_a_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemA), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_a_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_a_type_id;
		status_icon_a_menu_a_image_menu_item_a_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemA", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_a_type_id__volatile, status_icon_a_menu_a_image_menu_item_a_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_a_type_id__volatile;
}


static void __lambda4_ (StatusIconAMenuAImageMenuItemB* self) {
	StatusIconA* _tmp0_ = NULL;
	StatusIconA* _tmp1_ = NULL;
	_tmp0_ = status_icon_a_statusicon;
	_tmp0_->priv->paused = FALSE;
	_tmp1_ = status_icon_a_statusicon;
	gtk_status_icon_set_from_stock ((GtkStatusIcon*) _tmp1_, GTK_STOCK_MEDIA_PLAY);
}


static void ___lambda4__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda4_ ((StatusIconAMenuAImageMenuItemB*) self);
}


static StatusIconAMenuAImageMenuItemB* status_icon_a_menu_a_image_menu_item_b_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemB * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemB*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_MEDIA_PLAY, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "Start Commits");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda4__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemB* status_icon_a_menu_a_image_menu_item_b_new (void) {
	return status_icon_a_menu_a_image_menu_item_b_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_B);
}


static void status_icon_a_menu_a_image_menu_item_b_class_init (StatusIconAMenuAImageMenuItemBClass * klass) {
	status_icon_a_menu_a_image_menu_item_b_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_b_instance_init (StatusIconAMenuAImageMenuItemB * self) {
}


static GType status_icon_a_menu_a_image_menu_item_b_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_b_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_b_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemBClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_b_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemB), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_b_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_b_type_id;
		status_icon_a_menu_a_image_menu_item_b_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemB", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_b_type_id__volatile, status_icon_a_menu_a_image_menu_item_b_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_b_type_id__volatile;
}


static void __lambda5_ (StatusIconAMenuAImageMenuItemC* self) {
}


static void ___lambda5__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda5_ ((StatusIconAMenuAImageMenuItemC*) self);
}


static StatusIconAMenuAImageMenuItemC* status_icon_a_menu_a_image_menu_item_c_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemC * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemC*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_FULLSCREEN, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "Pull (Refresh) All");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda5__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemC* status_icon_a_menu_a_image_menu_item_c_new (void) {
	return status_icon_a_menu_a_image_menu_item_c_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_C);
}


static void status_icon_a_menu_a_image_menu_item_c_class_init (StatusIconAMenuAImageMenuItemCClass * klass) {
	status_icon_a_menu_a_image_menu_item_c_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_c_instance_init (StatusIconAMenuAImageMenuItemC * self) {
}


static GType status_icon_a_menu_a_image_menu_item_c_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_c_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_c_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemCClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_c_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemC), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_c_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_c_type_id;
		status_icon_a_menu_a_image_menu_item_c_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemC", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_c_type_id__volatile, status_icon_a_menu_a_image_menu_item_c_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_c_type_id__volatile;
}


static void __lambda6_ (StatusIconAMenuAImageMenuItemD* self) {
}


static void ___lambda6__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda6_ ((StatusIconAMenuAImageMenuItemD*) self);
}


static StatusIconAMenuAImageMenuItemD* status_icon_a_menu_a_image_menu_item_d_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemD * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemD*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_SAVE, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "Update Timesheet");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda6__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemD* status_icon_a_menu_a_image_menu_item_d_new (void) {
	return status_icon_a_menu_a_image_menu_item_d_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_D);
}


static void status_icon_a_menu_a_image_menu_item_d_class_init (StatusIconAMenuAImageMenuItemDClass * klass) {
	status_icon_a_menu_a_image_menu_item_d_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_d_instance_init (StatusIconAMenuAImageMenuItemD * self) {
}


static GType status_icon_a_menu_a_image_menu_item_d_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_d_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_d_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemDClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_d_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemD), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_d_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_d_type_id;
		status_icon_a_menu_a_image_menu_item_d_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemD", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_d_type_id__volatile, status_icon_a_menu_a_image_menu_item_d_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_d_type_id__volatile;
}


static void __lambda7_ (StatusIconAMenuAImageMenuItemE* self) {
}


static void ___lambda7__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda7_ ((StatusIconAMenuAImageMenuItemE*) self);
}


static StatusIconAMenuAImageMenuItemE* status_icon_a_menu_a_image_menu_item_e_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemE * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemE*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_FULLSCREEN, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "Manage Clones");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda7__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemE* status_icon_a_menu_a_image_menu_item_e_new (void) {
	return status_icon_a_menu_a_image_menu_item_e_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_E);
}


static void status_icon_a_menu_a_image_menu_item_e_class_init (StatusIconAMenuAImageMenuItemEClass * klass) {
	status_icon_a_menu_a_image_menu_item_e_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_e_instance_init (StatusIconAMenuAImageMenuItemE * self) {
}


static GType status_icon_a_menu_a_image_menu_item_e_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_e_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_e_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemEClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_e_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemE), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_e_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_e_type_id;
		status_icon_a_menu_a_image_menu_item_e_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemE", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_e_type_id__volatile, status_icon_a_menu_a_image_menu_item_e_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_e_type_id__volatile;
}


static void __lambda8_ (StatusIconAMenuAImageMenuItemF* self) {
	GtkAboutDialog* msg = NULL;
	GtkAboutDialog* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	_tmp0_ = (GtkAboutDialog*) gtk_about_dialog_new ();
	g_object_ref_sink (_tmp0_);
	msg = _tmp0_;
	gtk_about_dialog_set_program_name (msg, "Git Live");
	gtk_about_dialog_set_version (msg, "0.3");
	gtk_about_dialog_set_website (msg, "http://www.roojs.org/index.php/projects/gitlive.html");
	gtk_about_dialog_set_website_label (msg, "Roo J Solutions Ltd.");
	gtk_about_dialog_set_license (msg, "LGPL");
	_tmp1_ = g_strdup ("Alan Knowles <alan@roojs.com>");
	_tmp2_ = g_new0 (gchar*, 1 + 1);
	_tmp2_[0] = _tmp1_;
	_tmp3_ = _tmp2_;
	_tmp3__length1 = 1;
	gtk_about_dialog_set_authors (msg, _tmp3_);
	_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
	gtk_dialog_run ((GtkDialog*) msg);
	gtk_widget_destroy ((GtkWidget*) msg);
	_g_object_unref0 (msg);
}


static void ___lambda8__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda8_ ((StatusIconAMenuAImageMenuItemF*) self);
}


static StatusIconAMenuAImageMenuItemF* status_icon_a_menu_a_image_menu_item_f_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemF * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemF*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_ABOUT, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "About Gitlive");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda8__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemF* status_icon_a_menu_a_image_menu_item_f_new (void) {
	return status_icon_a_menu_a_image_menu_item_f_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_F);
}


static void status_icon_a_menu_a_image_menu_item_f_class_init (StatusIconAMenuAImageMenuItemFClass * klass) {
	status_icon_a_menu_a_image_menu_item_f_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_f_instance_init (StatusIconAMenuAImageMenuItemF * self) {
}


static GType status_icon_a_menu_a_image_menu_item_f_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_f_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_f_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemFClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_f_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemF), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_f_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_f_type_id;
		status_icon_a_menu_a_image_menu_item_f_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemF", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_f_type_id__volatile, status_icon_a_menu_a_image_menu_item_f_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_f_type_id__volatile;
}


static void __lambda9_ (StatusIconAMenuAImageMenuItemG* self) {
	gtk_main_quit ();
}


static void ___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda9_ ((StatusIconAMenuAImageMenuItemG*) self);
}


static StatusIconAMenuAImageMenuItemG* status_icon_a_menu_a_image_menu_item_g_construct (GType object_type) {
	StatusIconAMenuAImageMenuItemG * self = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp0_ = NULL;
	self = (StatusIconAMenuAImageMenuItemG*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	image = _tmp0_;
	gtk_image_set_from_stock (image, GTK_STOCK_QUIT, GTK_ICON_SIZE_MENU);
	gtk_image_menu_item_set_image ((GtkImageMenuItem*) self, (GtkWidget*) image);
	gtk_menu_item_set_label ((GtkMenuItem*) self, "Quit");
	gtk_image_menu_item_set_always_show_image ((GtkImageMenuItem*) self, TRUE);
	gtk_image_menu_item_set_accel_group ((GtkImageMenuItem*) self, NULL);
	g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) ___lambda9__gtk_menu_item_activate, self, 0);
	_g_object_unref0 (image);
	return self;
}


static StatusIconAMenuAImageMenuItemG* status_icon_a_menu_a_image_menu_item_g_new (void) {
	return status_icon_a_menu_a_image_menu_item_g_construct (STATUS_ICON_A_MENU_A_TYPE_IMAGE_MENU_ITEM_G);
}


static void status_icon_a_menu_a_image_menu_item_g_class_init (StatusIconAMenuAImageMenuItemGClass * klass) {
	status_icon_a_menu_a_image_menu_item_g_parent_class = g_type_class_peek_parent (klass);
}


static void status_icon_a_menu_a_image_menu_item_g_instance_init (StatusIconAMenuAImageMenuItemG * self) {
}


static GType status_icon_a_menu_a_image_menu_item_g_get_type (void) {
	static volatile gsize status_icon_a_menu_a_image_menu_item_g_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_image_menu_item_g_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAImageMenuItemGClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_image_menu_item_g_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuAImageMenuItemG), 0, (GInstanceInitFunc) status_icon_a_menu_a_image_menu_item_g_instance_init, NULL };
		GType status_icon_a_menu_a_image_menu_item_g_type_id;
		status_icon_a_menu_a_image_menu_item_g_type_id = g_type_register_static (GTK_TYPE_IMAGE_MENU_ITEM, "StatusIconAMenuAImageMenuItemG", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_image_menu_item_g_type_id__volatile, status_icon_a_menu_a_image_menu_item_g_type_id);
	}
	return status_icon_a_menu_a_image_menu_item_g_type_id__volatile;
}


static void status_icon_a_menu_a_class_init (StatusIconAMenuAClass * klass) {
	status_icon_a_menu_a_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = status_icon_a_menu_a_finalize;
}


static void status_icon_a_menu_a_instance_init (StatusIconAMenuA * self) {
}


static void status_icon_a_menu_a_finalize (GObject* obj) {
	StatusIconAMenuA * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, STATUS_ICON_A_TYPE_MENU_A, StatusIconAMenuA);
	_g_object_unref0 (self->pause);
	_g_object_unref0 (self->resume);
	G_OBJECT_CLASS (status_icon_a_menu_a_parent_class)->finalize (obj);
}


static GType status_icon_a_menu_a_get_type (void) {
	static volatile gsize status_icon_a_menu_a_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_menu_a_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAMenuAClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_menu_a_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconAMenuA), 0, (GInstanceInitFunc) status_icon_a_menu_a_instance_init, NULL };
		GType status_icon_a_menu_a_type_id;
		status_icon_a_menu_a_type_id = g_type_register_static (GTK_TYPE_MENU, "StatusIconAMenuA", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_menu_a_type_id__volatile, status_icon_a_menu_a_type_id);
	}
	return status_icon_a_menu_a_type_id__volatile;
}


static void status_icon_a_class_init (StatusIconAClass * klass) {
	status_icon_a_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (StatusIconAPrivate));
	G_OBJECT_CLASS (klass)->finalize = status_icon_a_finalize;
}


static void status_icon_a_instance_init (StatusIconA * self) {
	self->priv = STATUS_ICON_A_GET_PRIVATE (self);
	self->priv->paused = FALSE;
}


static void status_icon_a_finalize (GObject* obj) {
	StatusIconA * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_STATUS_ICON_A, StatusIconA);
	G_OBJECT_CLASS (status_icon_a_parent_class)->finalize (obj);
}


GType status_icon_a_get_type (void) {
	static volatile gsize status_icon_a_type_id__volatile = 0;
	if (g_once_init_enter (&status_icon_a_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatusIconAClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) status_icon_a_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusIconA), 0, (GInstanceInitFunc) status_icon_a_instance_init, NULL };
		GType status_icon_a_type_id;
		status_icon_a_type_id = g_type_register_static (GTK_TYPE_STATUS_ICON, "StatusIconA", &g_define_type_info, 0);
		g_once_init_leave (&status_icon_a_type_id__volatile, status_icon_a_type_id);
	}
	return status_icon_a_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



